name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./frontend --file Dockerfile --tag johnvincentjimar/greennotes-frontend:$(date +%s)

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./backend --file Dockerfile --tag johnvincentjimar/greennotes-backend:$(date +%s)
    
